### ISSUE TITLE
Color not working

### ISSUE THREAD

**Issue by thomas-lowry** [iconify/iconify-figma#1]
When I choose an icon, and add a hex value to the color input, it still inserts the icon as black.

![2019-07-30 08 00 10](https://user-images.githubusercontent.com/38481365/62127601-6fb2a180-b2a0-11e9-956c-2408fb8ce166.gif)

**Comment by cyberalien** [comment]
It requires # symbol for hex color. Field doesn't automatically assume there is # before value because it works with all valid colours.

I'll implement something to automatically add # for hexadecimal colours. Thanks for report!

**Comment by cyberalien** [comment]
Fixed
