### ISSUE TITLE
The end portion of the iconify plugin gets cut out on my 14 inch laptop(Thinkpad Win 10).

### ISSUE THREAD

**Issue by mukul23** [iconify/iconify-figma#11]
@cyberalien Great work on the figma plugin for iconify. Just one thing, on my 14 inch laptop(Thinkpad, Windows 10) the screen gets cut and I cannot select the options which are at the end(even after making Chrome full screen). I also cannot scroll past that point. Could you please look into it? Attaching image.
<img width="959" alt="udy9RWVS7s" src="https://user-images.githubusercontent.com/23497601/69003022-d5df3500-0920-11ea-8a9d-708e9d28371d.png">

**Comment by cyberalien** [comment]
Good news!

Version 2 of plug-in is almost ready, I plan to release it tomorrow. It uses much smaller interface and has option to make interface even smaller.

For comparison: 
Version 1 window is 800 x 800
Version 2 default mode window is 690 x 800
Version 2 compact mode window is 512 x 500

Screenshot of upcoming compact mode:
![Screen Shot 2019-11-17 at 09 27 27](https://user-images.githubusercontent.com/822287/69004483-8eef4080-091c-11ea-87a0-2b719c272c5e.png)

Also in version 2 you don't need to reach import button. It supports drag and drop, so you can drag icon directly from icons list to Figma document.

**Comment by mukul23** [comment]
Thanks a lot! Looks neat

**Comment by avsecuri** [comment]
This is exactly the problem I'm having, thanks to the author.

**Comment by cyberalien** [comment]
New version has been published. Please check if it solves your issue.
