### ISSUE TITLE
Enable sign in to Font Awesome for Pro Icons

### ISSUE THREAD

**Issue by ForgottenHero** [iconify/iconify-figma#17]
Could you please add sign-in feature for Font Awesome to allow accessing pro icons?

**Comment by cyberalien** [comment]
I will not be supporting any commercial icon sets for now.

In upcoming version of Iconify it is possible to add custom icon providers, allowing anyone to create their own version of Iconify, including premium icon set providers. However it will take at least few months until that functionality is fully ready.
