### ISSUE TITLE
Import a complete set or selected icons at once

### ISSUE THREAD

**Issue by pepas24** [iconify/iconify-figma#19]
I generally need to put the icons from Iconify as components to use them in other components and have the hability of swap between them. But search, import and make as component one by one is so tedious.

Will be posible to import a complete set of icons or the selected ones with just a click? Maybe the plugin can create a new frame with a grid (could be configurable x*x) of icons in the same order as in Iconify view.

**Comment by cyberalien** [comment]
That's a good idea. I'll see if it can be done. Selecting multiple icons for import would require some big changes.

As a workaround, install Scripter plug-in, then select icons you want to convert to components, open Scripter, paste this code:
```js
function nodeToComponent(frame) {
	if (!frame || frame.type !== 'FRAME') {
		return;
	}
	const component = figma.createComponent();
	component.resizeWithoutConstraints(frame.width, frame.height);
	for (const child of frame.children) {
  	component.appendChild(child);
	}
	component.name = frame.name;
	frame.parent.insertChild(getNodeIndex(frame), component);
	frame.remove();
}

function getNodeIndex(node) {
	const parent = node.parent;
	let index = 0;
	parent.children.forEach((node2, index2) => {
		if (node2.id === node.id) {
			index = index2;
		}
	});
	return index;
}

figma.currentPage.selection.forEach(nodeToComponent);

```
and run it.

It should convert all selected frames to components.

**Comment by pepas24** [comment]
Thanks for response.
My issue is not about make all frames as components, due to Figmas has a buit-in action for do that (Create Multiple Components in the top bar), but the pain of search, drag and drop one by one from the plugin window. But thanks for the script this can help me in other situations.

**Comment by joelbqz** [comment]
Hey, @cyberalien what about adding an option to import as component?
http://drop.frontporchsolutions.com/4PzOEr

**Comment by cyberalien** [comment]
A quick note that I didn't forget it, just very very slowly working on it.

Currently I'm working on completely new version of plug-in, it will have option to import component. Adding new features to old code would take time from development, so it would be better to spend time developing new version. Until then action mentioned by @pepas24 should work well.

**Comment by cyberalien** [comment]
Implemented in new version of plugin:
- Select multiple icons and import them.
- Import as component.
- Replace icon.

New version will be published next week.
