### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by lifeinchords** [iconify/iconify-figma#2]
Hi there,

Awesome plugin!

One issue I run into - when I enter the plugin the first thing I do is start typing, expecting the focus to be in the search form.

Since it isn't, whatever I type passes through to Figma as key commands, and I quickly end up somewhere else in my board, on another frame, deleting things, etc. I then close the plugin, find my way back, undo everything and start over.

Can you add focus into the form field ?

**Comment by cyberalien** [comment]
That's a very good idea. Thanks!

Implemented. Restart Figma to see changes.

**Comment by lifeinchords** [comment]
Lovely! 💯
Thanks for the super quick response/implement.
