### ISSUE TITLE
Icon Library Request

### ISSUE THREAD

**Issue by forestwas** [iconify/iconify-figma#22]
I would like to see the Phosphor icon library in Iconify: https://phosphoricons.com/

**Comment by cyberalien** [comment]
That's a good icon set with open source license. I'll add it.

However it will take a while. Problem is with icon variations. All other icon sets that have variations, such as Material Design Icons, use suffixes (or prefixes) for all icons. Phosphor uses suffixes for all icons, except for default icon set.

I didn't account for that when coding search engine, so it will need some tweaks. Now that I think of it, it totally makes sense, so I should have accounted for possibility of icon variations without suffix, but I didn't. Easiest workaround is to add suffix, which would be easy, but I'd rather do it properly, which will take some time.

**Comment by forestwas** [comment]
Thank you, Vjacheslav! Looking forward to getting it!

I can not tell how Iconify has changed my design process and is saving me a great amount of time ♥️ One of the best plugins so far for me 👊

**Comment by cyberalien** [comment]
Thank you!

**Comment by cyberalien** [comment]
Added.

In current version of Figma plug-in icons will show up as one big list, without option to filter by theme. New version that is currently in development will display Phosphor Icons properly.

**Comment by forestwas** [comment]
@rektdeckard Great icon set, man 👏

@cyberalien many thanks 🙏

**Comment by rektdeckard** [comment]
@forestwas pleasure to be of service 💅
