### ISSUE TITLE
Cannot 'reset'/select all filters under "filter by tag"

### ISSUE THREAD

**Issue by brascosDad** [iconify/iconify-figma#23]
in Iconify for Figma I was able to click on a tag, but now I can't select more than 1 tag.

**Comment by cyberalien** [comment]
Click selected tag again.

**Comment by brascosDad** [comment]
thank you!

**Comment by cyberalien** [comment]
Glad it worked, I was afraid there is some weird bug.

UI needs to be improved to make it clearer.

Also, if something goes wrong, you can reset plug-in UI. Click menu button (3 lines) in top left corner, you'll see sub-menu below it. On right side there is a "Reset" link that resets all plug-in settings to default.
