### ISSUE TITLE
A set might be a good addition

### ISSUE THREAD

**Issue by forestwas** [iconify/iconify-figma#24]
https://github.com/artcoholic/akar-icons#readme

I recently stumbled upon the icon set above. You may want to consider it to add into Iconify.

✌️

**Comment by cyberalien** [comment]
Added.

It is a very good icon set. MIT License and icon set is maintained, so it is a great addition.

It should appear in Figma plug-in as soon as browser and/or Cloudflare (set to 4 hours, so depending on when it was cached it might be instant or might take a while) caches expire.
