### ISSUE TITLE
Option to close plugin window after import

### ISSUE THREAD

**Issue by hmaesta** [iconify/iconify-figma#25]
Would be nice an option to, by default, close plugin window after clicking "Import icon".

**Comment by cyberalien** [comment]
Good idea. I'll keep this issue open to make sure I won't forget to add it to next version.

**Comment by cyberalien** [comment]
Implemented in new version of plugin.

New version is a full rewrite of plugin and it is currently in development. It will be published when it reaches feature parity with old version.
