### ISSUE TITLE
Deleted icons are displayed on present screen

### ISSUE THREAD

**Issue by IconStudiosNY** [iconify/iconify-figma#26]
Hi,

I dragged some icons into my screen and deleted them but they still show up in the preview page.

I have no way of removing or editing the icons as I don't see it the edit page and it is not in the layers section either.

This literally ruins my prototype presentation.

See attached screenshot.

Thank you.

![Screen Shot 2021-06-09 at 5 46 40 PM](https://user-images.githubusercontent.com/18406210/121434694-b1f0a380-c94b-11eb-853c-de6133400c99.png)

**Comment by cyberalien** [comment]
So icon layers are no longer there, but they are still showing up in presentation?

**Comment by IconStudiosNY** [comment]
> So icon layers are no longer there, but they are still showing up in presentation?

Correct

**Comment by IconStudiosNY** [comment]
Interestingly enough, I just closed Figma and restated the application and the icons reappeared on the project edit screen where I'm now able to delete it

**Comment by cyberalien** [comment]
Looks like something went wrong in Figma. Maybe cache issue, maybe something else.

All plugin does is adds a group of layers when you import icon. When you delete it, it is done by Figma like with any other group of layers.
