### ISSUE TITLE
Go to pack?

### ISSUE THREAD

**Issue by AnastasiyChertovich** [iconify/iconify-figma#28]
Hello. how now, when selecting one icon, go to its pack?

**Comment by cyberalien** [comment]
I'm not sure what you are asking.

How to view icon set selected icon belongs to? There is no direct link, you need to return to collections list then click icon set. To find icon set faster, type name (or part of name - search works instantly) in "Filter collections" field.
![filter-collections](https://user-images.githubusercontent.com/822287/144570337-e9224de6-5808-4649-9682-0e3276520d48.png)

**Comment by AnastasiyChertovich** [comment]
Oy, thanks you,it used to be like this (
You find the icon you need by searching. Then there was a link to the entire pack of icons

**Comment by cyberalien** [comment]
From search results there are links to packs. Switch to list mode (button in top right corner of icons list)

**Comment by AnastasiyChertovich** [comment]
Thanks you!
