### ISSUE TITLE
Not working at the moment

### ISSUE THREAD

**Issue by CasanovaSekova** [iconify/iconify-figma#29]
Hi, when I run Iconify as a plug-in, it shows the "Running Iconify" indefinitely without showing the window to select an icon
![image](https://user-images.githubusercontent.com/95392008/147428982-405b3350-7418-428f-82fd-b560781ebc53.png)

**Comment by cyberalien** [comment]
Sometimes this happens to all plugins in Figma. If UI didn't appear, something went wrong when Figma was loading plugin. Most likely it failed to load plugin UI from AWS, where Figma hosts all plugins.

Restart Figma. If error persists, in menu go to `plugins -> development -> open console`, then try to run plugin. It might show you exact error message.

**Comment by CasanovaSekova** [comment]
Perfect, thank you so much. Sorry about that as I've just started using Figma
