### ISSUE TITLE
Icons are being placed incorrectly

### ISSUE THREAD

**Issue by M-axD** [iconify/iconify-figma#3]
When adding icons, some are placed missing lines and are incomplete. This only happens on certain icons.
<img width="997" alt="Screen Shot 2019-09-05 at 2 00 37 PM" src="https://user-images.githubusercontent.com/54956131/64367169-aab59c80-cfe5-11e9-9711-403ebcd09a7a.png">

**Comment by cyberalien** [comment]
Its something that Figma team broke when importing SVG. Many icons that were working correctly last week are now bugged.

I've made a bug report, hopefully they'll fix it soon.

**Comment by M-axD** [comment]
Oh okay perfect. Thank you for the response
