### ISSUE TITLE
Typo when previewing an icon before inserting into Figma.

### ISSUE THREAD

**Issue by pazeeee** [iconify/iconify-figma#30]
In the Iconify Figma plugin, there is a typo in the preview section of every icon. In this section, there is a description to the icon, that is supposed to say "About" but in the new Iconify for Figma update, it says "Aboout".
![image](https://user-images.githubusercontent.com/84513294/147991598-c6920886-c0dc-418b-a7dd-4aa57d81ccee.png)

**Comment by cyberalien** [comment]
Thanks a lot for reporting!

Fixed.
