### ISSUE TITLE
import icons

### ISSUE THREAD

**Issue by amir9675** [iconify/iconify-figma#34]
first of all thanks for every thing, i can not import my own icon pack into the plugin. i click on import but there is no response. what can i do? 
have a nice day

**Comment by cyberalien** [comment]
Import button imports selected icon to Figma.

You cannot use this plugin with your own icon packs yet, for now it works only with pre-approved open source icon sets. If you do want to add your icon set to Iconify (it will be available not only in Figma plugin, but also as components for thousands of developers who using Iconify Icon components, Unplugin Icons, UnoCSS, Astro Icon and some other similar icon components). See https://docs.iconify.design/articles/add-icon-set/ for details.
