### ISSUE TITLE
Bollen groupped / Masked icons don't work properly

### ISSUE THREAD

**Issue by bencehusi** [iconify/iconify-figma#35]
When selecting an icon that has a masked shape or a boolean group - e.g., in case of an outline icon - the imported icon's shapes don't have the mask / boolean group applied.

Most icon libraries are affected.

Figma: 114.4 on a MacBook Pro (12.3.1)

See videocast:
https://www.loom.com/share/3d24cfb008074f31b07792b13fc7b079

**Comment by cyberalien** [comment]
Thank you very much for reporting this!

It was a regression, caused by my implementation of a workaround for bug in Figma when importing complex shapes with stroke.

Fixed. Restart Figma to update plugin.
