### ISSUE TITLE
Could not connect to Iconify API. from firefox

### ISSUE THREAD

**Issue by timondigital** [iconify/iconify-figma#36]
Good morning, I have this problem but only from firefox, if I open the project in chrome there is no drama, do you have any idea that it may be blocking the connection from this browser?

thank you

**Comment by cyberalien** [comment]
Try accessing https://api.iconify.design/version

If you can, API is not the issue, but something else is causing errors. Maybe an add-on or something.

**Comment by timondigital** [comment]
When I enter, this appears: 
Iconify API version 2.0.4 (Node, DE)

**Comment by timondigital** [comment]
Must be some add-on then...

**Comment by cyberalien** [comment]
Where are you accessing it from? Your profile shows that you are from Argentina, but that log message shows you are connected to German server. There are closer servers in US that you should be connected to.

Maybe you are using some proxy service?

**Comment by timondigital** [comment]
I'm from Argentina, but I don't know why the server will be German... can that cause the problem? because I am not using any proxy that I have configured.

Where could I check that? or is it the internet company that configures it?

I tried to disable the extensions that I have installed in firefox and still the same error...

**Comment by cyberalien** [comment]
I've recently restructured API servers network a bit, added a new server that should handle all users from South America. Actual server for South American users is based in Texas because I couldn't find a reliable and reasonably priced VPS provider anywhere closer, but it should be good enough.

So I think this issue should be solved.
