### ISSUE TITLE
Import icon in current view or let user click location of icon

### ISSUE THREAD

**Issue by WouS95** [iconify/iconify-figma#37]
I use this plugin often it's really great!
The only issue I have is that when importing an icon and an artboard is not selected the icon appears far away from where I am at.
I have to zoom out en pan to the far right all the way to the last artboard to try and find the icon i just imported. 
Sometimes I can't find the icon and it appears a few days later because it was such a small icon and i just lost it.

Is it possible to import the icon in the current view when zoomed in, or maybe first import it, not placing it yet and then let the user click on the position where the icon needs to be? This would save a lot of time searching, copying and pasting the icon in the right spot.

Thanks!

**Comment by cyberalien** [comment]
I think this can be done. Will test it.

**Comment by cyberalien** [comment]
So I have mix of bad and good news.

Bad news is it would be very tricky to do with current version of plugin. It is based on spaghetti code, which is hard to maintain and modify, so changing target layer function might end up breaking something else. Current version of plugin is my first attempt at working with Svelte and I've made few critical errors when designing it, in both Svelte code and library that handles all other stuff.

Good news is I'll add it to next major version of plugin. Currently I'm in process of rewriting code that plugin is based on, which will address issues of spaghetti code and maintainability. Unfortunately it will take a while.

**Comment by WouS95** [comment]
Allright! Thank you for your explanation. Good luck with the new version :) looking forward to it!

**Comment by cyberalien** [comment]
Implemented in new version of plugin.

If importing to page, it will import to middle of viewport.

Also drag and drop is now precise, so you can drag/drop icon from plugin to wherever you want it to be. Though location might be messed up if you are using auto-layout - it will import as first element in group/frame/section that is located at drop coordinates, but still close enough.
