### ISSUE TITLE
Batch export to a iconify icon set

### ISSUE THREAD

**Issue by xypnox** [iconify/iconify-figma#39]
To generate a custom iconify icon set a user currently has to setup a pipeline for figma via https://docs.iconify.design/tools/tools2/import/figma/.

This whole process can be simplified if the iconify plugin allowed users to select a set of frames/components and export them to a custom icon set.

The icon set could then be created from figma directly rather than setting up a pipeline for the same.

**Comment by cyberalien** [comment]
I do want to do that, but it will take a while.

**Comment by cyberalien** [comment]
Finally got to rewriting plugin. 

It does not have batch export, but it does have a button to select all visible icons and new icons list layout with quick scrolling. This should make it much easier to import whole icon set.

Preview of new version is available in this repository.
