### ISSUE TITLE
Jam Icons by Michael Aprimo appearing distorted

### ISSUE THREAD

**Issue by janjanlee123** [iconify/iconify-figma#4]
![image](https://user-images.githubusercontent.com/54929212/64455989-b6bc5f80-d0b4-11e9-8780-22b86741660a.png)

**Comment by cyberalien** [comment]
It currently happens to a lot of icons. Code that imports SVG was broken in latest Figma update. Figma developers are working on fixing it.

**Comment by cyberalien** [comment]
Fixed in latest Figma update.
