### ISSUE TITLE
"Import as Component" adds component icon only outside a section

### ISSUE THREAD

**Issue by aliceabsolvome** [iconify/iconify-figma#43]
Not sure if an iconify issue or a Figma issue. 

**Steps:** 
1. Create a large section in Figma
2. Place your cursor inside the section, do something in it, create a frame maybe.  
3. Open Iconify 
4. Find an icon
5. Click "Import as Component" 

**Expected Result:** the icon appears somewhere near the work area. 
Optimal: inside the selected frame. 
Acceptable: Right outside the selected frame. 

**Actual Result:** The icon appears only at the end of the section you are in. 
In my case, I'm working on a very large section and the teeny-tiny icon appears at the very end somewhere. I have to go ahead and find it like with a microscope and then manually copy+paste or drag it to where I need it to be.

**Comment by cyberalien** [comment]
Thanks for report!

Sections are rather new addition to Figma, it is not supported by plugin yet.

I'm in process of rewriting plugin, new version will account for sections.

**Comment by cyberalien** [comment]
Fixed in version 3 (preview is available in this repository)
