### ISSUE TITLE
Add licence link to plugin

### ISSUE THREAD

**Issue by Epskampie** [iconify/iconify-figma#5]
Hi, awesome plugin, use it all the time, thanks for making it.

Would love to see a "license" link added when previewing an icon so that I can check if I can use it in my commercial projects. I see that you do already show this information on your website: https://iconify.design/icon-sets/wpf/airplane-takeoff.html

**Comment by cyberalien** [comment]
Its coming in next version.

See Figma plug-in show and tell from last week, where I talk about changes and new upcoming features (also other Figma plug-in developers talk about their plug-ins): https://www.youtube.com/watch?v=i6ppX9fjXz0

Also preview of updated UI: https://iconify.design/test/figma-demo.html

**Comment by Epskampie** [comment]
Nice, good to hear! I will watch that youtube link, seems fun as I made my own (pretty simple) plugin as well: https://www.figma.com/c/plugin/738791203005929386/Add-numbers-to-texts :grin:
