### ISSUE TITLE
icons are showing up greatly distorted

### ISSUE THREAD

**Issue by markabarrett** [iconify/iconify-figma#7]
I am importing a number of social icons from different libraries but all of the icons are coming out corrupted
<img width="652" alt="Screen Shot 2019-09-13 at 11 00 06 AM" src="https://user-images.githubusercontent.com/29001621/64884122-c63c2b00-d615-11e9-9af2-82bf08d02a20.png">

**Comment by cyberalien** [comment]
It was a bug in SVG importer in Figma. It was fixed few days ago, so updating to latest version of desktop app should fix it.
