### ISSUE TITLE
Add "next/prev" buttons in pagination

### ISSUE THREAD

**Issue by pepas24** [iconify/iconify-figma#8]
Sometimes I'm not searching for a partricular icon, insted I'm viewing the icon library in general, but I have to move the cursor between each number in pagination, so wil be greet if has a "next/prev" buttons.

Thanks for the hard work!

**Comment by cyberalien** [comment]
Good idea. Thanks!

Added in next version. I'm working on complete rewrite of UI, so it will take a while for it to be released.
